version: 2.1

executors:
  docker:
    docker:
      - image: cimg/base:2023.07

jobs:
  pwd:
    executor: docker
    steps:
      - setup_remote_docker
      - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
      - run: git submodule init
      - run: git submodule update
      - run: pwd
      - run: ls -la
      - run: ls karsajobs

  lint-dockerfile:
    executor: docker
    parameters: 
      directory:
        type: string
    steps:
      - setup_remote_docker
      - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
      - run: git submodule init
      - run: git submodule update
      - run: docker run --rm --interactive hadolint/hadolint < ./<< parameters.directory >>/Dockerfile
  
  test-app:
    executor: docker
    steps:
      - setup_remote_docker
      - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
      - run: git submodule init
      - run: git submodule update
      - run: cd karsajobs && go test -v -short --count=1 $(go list ./...)


  build-app-karsajobs:
    executor: docker
    steps:
      - setup_remote_docker
      - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
      - run: git submodule init
      - run: git submodule update
      - run: cd karsajobs && /bin/bash build_push_image_karsajobs.sh

  build-app-karsajobs-ui:
    executor: docker
    steps:
      - setup_remote_docker
      - run: git clone -b "$CIRCLE_BRANCH" "$CIRCLE_REPOSITORY_URL" .
      - run: git submodule init
      - run: git submodule update
      - run:
          name: Run Builder Script
          command: cd karsajobs-ui && /bin/bash build_push_image_karsajobs_ui.sh

workflows:
  karsajobs-workflow:
    jobs:
      - pwd
      - lint-dockerfile:
          directory: karsajobs
      - test-app
      - build-app-karsajobs 

  karsajobs-ui-workflow:
    jobs:
      - pwd
      - lint-dockerfile:
          directory: karsajobs-ui
      - build-app-karsajobs-ui
